### ISSUE TITLE
[FEATURE] Automated release created in github when change on master

### ISSUE THREAD

**Issue by lawrencegripper** [databrickslabs/terraform-provider-databricks#117]
**Is your feature request related to a problem? Please describe.**

Would be great to get an automated process setup which creates a release when a change is put onto `master`

**Describe the solution you'd like**

In the past I've used [goreleaser]() to build out a nice release process for [azbrowse](https://github.com/lawrencegripper/azbrowse/blob/master/.goreleaser.yml). I'd be happy to do a PR with this to integrate into the [travis build](https://goreleaser.com/ci/travis/)

**Describe alternatives you've considered**

You can build out this process yourself but it's kind of a pain to do and go releaser makes like easy.

**Comment by stikkireddy** [comment]
Hey @lawrencegripper I understand the want to create a release per merge to master but since we are not using release branches at this point in time, till we get to a stable version of this provider. It will create a release & tag per pr. It may become overwhelming in terms of deciding to use and update the provider (especially since you would need to refresh every time). I was hoping we can follow tag convention that this provider uses https://github.com/terraform-providers/terraform-provider-azurerm/releases. 

I am totally for this enhancement in regards to automating the release process but I was wondering if there would be a way to do something like the azurerm and some of the other providers in terms of semver and each release being a collection of changes/fixes rather than a release tag per PR. Thats just my $0.02.

I will let other folks chime in on this as well @nfx @stuartleeks

**Comment by stuartleeks** [comment]
If the small incremental releases typically just result in a change to the patch number (e.g. `0.2.1`, `0.2.2`, or `0.2.<buildnum>`) then I'm onboard with this. Users can easily pick a version (`=0.2.0`) if they want to, or just opt for latest path for a specific minor version (`~>0.2`) depending on their preferences for consuming updates. But at least by making releases available you give users a way to get fixes and new features quickly if they want them.

**Comment by lawrencegripper** [comment]
As discussed in the linked PR the proposal is to move to a 7 day automated release cycle (if changes are present) potentially using GitHub Actions.

**Comment by nfx** [comment]
@lawrencegripper 7-day automated release cycle using github actions is an interesting idea.

having release per PR is something we cannot yet afford maintaining.
