### ISSUE TITLE
[ISSUE] Can't manage sql permissions on workspace's hive_metastore

### ISSUE THREAD

**Issue by ebarault** [databrickslabs/terraform-provider-databricks#1216]
### Configuration
```hcl
resource "databricks_sql_permissions" "permissions" {
  catalog = true

  privilege_assignments {
    principal  = "hive_metastore_users"
    privileges = ["USAGE", "CREATE", "SELECT", "MODIFY"]
  }
}
```

### Expected Behavior
Grant "USAGE", "CREATE", "SELECT", "MODIFY" privileges to principal "hive_metastore_users" on workspace's local hive_metastore

### Actual Behavior
> Error: cannot create sql permissions: cannot read current grants: For unity catalog, please specify the catalog name explicitly. E.g. SHOW GRANT `your.address@email.com` ON CATALOG main

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions
databricks provider 0.5.4

### Notes
Unity Catalog is activated on this workspace (although what i'm dealing with here is indeed the workspace's own hive metastore)

### Cluster logs
```
...
22/03/23 15:16:04 INFO DriverDaemon: Starting driver daemon...
22/03/23 15:16:04 INFO SparkConfUtils$: Customize spark config according to file /tmp/custom-spark.conf
22/03/23 15:16:04 WARN SparkConf: The configuration key 'spark.akka.frameSize' has been deprecated as of Spark 1.6 and may be removed in the future. Please use the new key 'spark.rpc.message.maxSize' instead.
22/03/23 15:16:04 INFO DriverDaemon$: Attempting to run: 'enable iptables restrictions for Python'
22/03/23 15:16:05 INFO DriverDaemon$: Attempting to run: 'set up filesystem permissions for Python'
22/03/23 15:16:13 INFO DriverDaemon$: Not configuring RStudio Daemon due to process isolation being enabled
22/03/23 15:16:13 INFO DriverDaemon$$anon$1: Message out thread ready
22/03/23 15:16:13 INFO Server: jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 1.8.0_302-b08
22/03/23 15:16:13 INFO AbstractConnector: Started ServerConnector@4ee80a94{HTTP/1.1, (http/1.1)}{0.0.0.0:6061}
22/03/23 15:16:13 INFO Server: Started @39775ms
22/03/23 15:16:13 INFO DriverDaemon: Driver daemon started.
22/03/23 15:16:14 WARN SQLConf: The SQL config 'spark.sql.hive.convertCTAS' has been deprecated in Spark v3.1 and may be removed in the future. Set 'spark.sql.legacy.createHiveTableByDefault' to false instead.
22/03/23 15:16:14 WARN SQLConf: The SQL config 'spark.sql.hive.convertCTAS' has been deprecated in Spark v3.1 and may be removed in the future. Set 'spark.sql.legacy.createHiveTableByDefault' to false instead.
22/03/23 15:16:15 INFO DriverCorral: Loading the root classloader
22/03/23 15:16:15 INFO DriverCorral: Starting sql repl ReplId-5a32f-09fc8-c75ef
22/03/23 15:16:15 INFO DriverCorral: Starting sql repl ReplId-51c66-bc70c-e5f4e-0
22/03/23 15:16:15 INFO DriverCorral: Starting sql repl ReplId-709fc-9921d-57f98-7
22/03/23 15:16:15 INFO DriverCorral: Starting sql repl ReplId-2572e-6c0cf-40855-5
22/03/23 15:16:15 INFO DriverCorral: Starting sql repl ReplId-78129-45ef2-6ec20-2
22/03/23 15:16:15 INFO SQLDriverWrapper: setupRepl:ReplId-5a32f-09fc8-c75ef: finished to load
22/03/23 15:16:15 INFO SQLDriverWrapper: setupRepl:ReplId-2572e-6c0cf-40855-5: finished to load
22/03/23 15:16:15 INFO SQLDriverWrapper: setupRepl:ReplId-709fc-9921d-57f98-7: finished to load
22/03/23 15:16:15 INFO SQLDriverWrapper: setupRepl:ReplId-78129-45ef2-6ec20-2: finished to load
22/03/23 15:16:15 INFO SQLDriverWrapper: setupRepl:ReplId-51c66-bc70c-e5f4e-0: finished to load
22/03/23 15:16:38 WARN SQLConf: The SQL config 'spark.sql.hive.convertCTAS' has been deprecated in Spark v3.1 and may be removed in the future. Set 'spark.sql.legacy.createHiveTableByDefault' to false instead.
22/03/23 15:16:38 WARN SQLConf: The SQL config 'spark.sql.hive.convertCTAS' has been deprecated in Spark v3.1 and may be removed in the future. Set 'spark.sql.legacy.createHiveTableByDefault' to false instead.
22/03/23 15:16:38 INFO DriverCorral: Starting sql repl ReplId-7e3e3-a44e4-e3042-6
22/03/23 15:16:38 INFO SQLDriverWrapper: setupRepl:ReplId-7e3e3-a44e4-e3042-6: finished to load
22/03/23 15:16:39 INFO ProgressReporter$: Added result fetcher for 9096772364907250726_7707065032651177604_64d0ce73-5660-48a3-ab28-48282cc0f069
22/03/23 15:16:40 ERROR SQLDriverLocal: Error in SQL query: SHOW GRANT ON CATALOG 

org.apache.spark.sql.AnalysisException: For unity catalog, please specify the catalog name explicitly. E.g. SHOW GRANT `your.address@email.com` ON CATALOG main
	at com.databricks.sql.managedcatalog.ManagedCatalogErrors$.shouldSpecifyTheCatalogName(ManagedCatalogErrors.scala:75)
	at com.databricks.sql.acl.CatalogSecurableIdentifier.toV1orV2Securable(statements.scala:57)
	at com.databricks.sql.acl.ResolvePermissionManagement.apply(ResolvePermissionManagement.scala:53)
	at com.databricks.sql.acl.ResolvePermissionManagement.apply(ResolvePermissionManagement.scala:34)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$3(RuleExecutor.scala:216)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	...
```

**Comment by nfx** [comment]
@ebarault I'm on vacation till April 12 ;) no release until that week. Only merges of PRs.

And is this error happening on "default technical cluster" created by terraform (eg no cluster id specified in resource) or on unity catalog enabled cluster? 

Because Table ACL syntax doesn't expect a catalog name in SQL statements. Do some debug logging together with your solutions architect and file a support ticket.

**Comment by ebarault** [comment]
have nice vacations @nfx 
this error happens on both clusters type, i first let the resource run its own default cluster, and then tried with different set of clusters (runtimes, instance profiles, etc.)

I filed a support ticket and referenced this github issue within.

**Comment by nfx** [comment]
@ebarault Thank you. 

Theoretically what might work is creating a cluster with pre-UC runtime, like 9.1LTS and specifying it as cluster_id attribute on the resource, so that you know for sure it runs on TACL HC cluster. You should also be able to get SQL command sequence from debug logs, when collaborating with support.

Keep in mind that TACL and UC security models are different and you may need to use different grants.

**Comment by nfx** [comment]
@ebarault Can you post debug logs from tf provider, not spark deiver?

**Comment by ebarault** [comment]
here you go @nfx 
[trace.txt](https://github.com/databrickslabs/terraform-provider-databricks/files/8396912/trace.txt)

**Comment by nkvuong** [comment]
the issue here is because the config for a TACL cluster is different when Unity Catalog is enabled
For workspaces without Unity Catalog, it is `"spark.databricks.acl.dfAclsEnabled": "true"`
For workspaces with Unity Catalog, it is `"data_security_mode": "LEGACY_TABLE_ACL"` or `"data_security_mode": "USER_ISOLATION"`

The fix here is to provide a cluster with the correct config in Unity Catalog, but we need to relax the check on the provider

**Comment by nfx** [comment]
@nkvuong can you add a documentation on sql_permissions resource for this edge case of UC-enabled customers? :)

**Comment by ebarault** [comment]
hi @nkvuong ,
I just tested this and I get exactly the same error:
```
Error: cannot create sql permissions: cannot read current grants: For unity catalog, please specify the catalog name explicitly. E.g. SHOW GRANT `your.address@email.com` ON CATALOG main
```

**Comment by nkvuong** [comment]
@ebarault interesting - could you check a few things for me, with a notebook attached to the tacl cluster just created. 
`%sql SHOW GRANT ON CATALOG` - I assume this would throw the UC error

`%python spark.conf.get("spark.databricks.sql.initial.catalog.name")` - what is the output of this command

**Comment by ebarault** [comment]
I'm doing this right now.
in the meantime, there's a gap between what you said earlier :
> For workspaces with Unity Catalog, it is "data_security_mode": "LEGACY_TABLE_ACL" or "data_security_mode": "USER_ISOLATION"

and the example you provided:
```
spark_conf = {
    "spark.databricks.acl.dfAclsEnabled" : "true",
}
```
So I also tested with 
```
"data_security_mode": "LEGACY_TABLE_ACL" or "data_security_mode": "USER_ISOLATION"
```

but then I get the following error :
`cannot create sql permissions: cluster_id: not a High-Concurrency cluster`

**Comment by ebarault** [comment]
@nkvuong 
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/12000935/164690778-35541108-fc91-4766-97bf-b7b812b7b1bf.png">

<img width="519" alt="image" src="https://user-images.githubusercontent.com/12000935/164691324-cd85d21e-1165-4346-a516-437da5a658f5.png">

**rd** is the name of our default UC catalog

**Comment by nkvuong** [comment]
@ebarault so I was wrong about the cluster config, both types of config are still valid, i.e. they both create TACL clusters

The issue here is because of the default catalog name, [TACL commands](https://docs.databricks.com/security/access-control/table-acls/object-privileges.html) such as `SHOW GRANT ON CATALOG` only assumes 2L namespace because there is a single catalog `hive_metastore`

When UC is enabled on a workspace, TACL commands then use the default catalog name, which is normally set to `hive_metastore`. Any other UC catalog set as default will break these TACL commands, and thus breaks **databricks_sql_permissions** resources

Fixing this directly in the provider will be complex, as we need different paths for UC & non-UC workspaces.

As a workaround, I would suggest the following:
- To set the default UC catalog, you shouldn't need a global init script. Instead this can be set across the whole workspace using [databricks-cli-uc](https://pypi.org/project/databricks-cli-uc/)
```
databricks-cli assign-metastore --workspace-id WORKSPACE_ID  --metastore-id METASTORE_ID --default-catalog-name DEFAULT_CATALOG_NAME
```
- Then you should be able to apply TACL with this cluster
```hcl
resource "databricks_cluster" "tacl" {
  cluster_name            = "tacl"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 2
  }
  spark_conf = {
    "spark.databricks.acl.dfAclsEnabled" : "true",
    "spark.databricks.repl.allowedLanguages" : "python,sql",
    "spark.databricks.sql.initial.catalog.name": "hive_metastore"
  }
}
```

**Comment by ebarault** [comment]
@nkvuong, ok, just setting `"spark.databricks.sql.initial.catalog.name": "hive_metastore"` in the tacl cluster is enough, I don't need to change my config (global init script vs. default catalog at metastore assignment), but I take note of the suggetion though

Thank you 👍

**Comment by ebarault** [comment]
@nkvuong @nfx I reviewed the changes on the doc. 
I think it really misses the bits about 
```
resource "databricks_cluster" "tacl" {
  cluster_name            = "tacl"
 ...
 spark_conf = {
    "spark.databricks.acl.dfAclsEnabled" : "true",
    "spark.databricks.repl.allowedLanguages" : "python,sql",
    "spark.databricks.sql.initial.catalog.name": "hive_metastore"
  }
}
```

**Comment by nkvuong** [comment]
@ebarault the official guideline from the product team is to set `default_catalog_name` to `hive_metastore` to prevent incompatibility issues - hence keeping this workaround in the issue only
