### ISSUE TITLE
[Feature] Add obo token creation for Azure Databricks

### ISSUE THREAD

**Issue by hwang74** [databrickslabs/terraform-provider-databricks#1312]
Hi there,

To create a PAT on behalf of a service principal, I need to write a custom script to 
1. call Azure AD Token API to get an Azure AD access token with client_credential flow for the SPN
2. authenticate with Databricks API with the Azure AD access token
3. call Databricks Token 2.0 API to create a token 

These steps can be internalized for databricks_obo_token resource to support Azure

**Comment by alexott** [comment]
@hwang74 OBO tokens aren't supported on Azure. Creating a separate resource won't help you much because you will need to use SP authentication anyway.  But you may have a workaround for that using Terraform:

1. Have a separate Terraform code that will generate PAT using SP AAD token and put it somewhere, like, Azure KeyVault, and then another Terraform code that will grab that token from Azure KeyVault. Something like this: https://github.com/databrickslabs/overwatch/blob/main/terraform/azure/job/secrets.tf#L16

2. Have two modules with two different Databricks providers declarations - one using AAD auth will generate a PAT, and return it, and second module - use that PAT.

**Comment by alexott** [comment]
There is a difference between SP that can generate a PAT for **itself** (using AAD token) vs OBO token that is generated by **admin user for SP**. These are different patterns, and using the same resource for completely different functionality is incorrect. On Azure we don't have a way for generating OBO token primarily because we have AAD auth for service principals - the functionality that is missing on AWS.

I don't see the problem with existing functionality - it's fully supported on Azure, but specifics of integration is heavily dependent on the specific use case.
