### ISSUE TITLE
[Feature] databricks_git_credential provide personal_access_token through env variable

### ISSUE THREAD

**Issue by Freia3** [databrickslabs/terraform-provider-databricks#1352]
Right now, the databricks_git_credential resource has to be declared like this:
### Configuration
```hcl
resource "databricks_git_credential" "ado" {
  git_username          = "myuser" 
  git_provider          = "azureDevOpsServices"
  personal_access_token = "sometoken"
}
```
Would it be possible to make personal_access_token optional and if it's not provided, make it look in the environment variables? The personal access token for azure devops is saved in AZDO_PERSONAL_ACCESS_TOKEN and I would like to use this environment variable to declare the databricks_git_credential resource.

**Comment by nfx** [comment]
@Freia3 it's a very good suggestion, we can definitely pick PAT from the list of environment variables. In order to speed up the implementation of this feature, could you do some research and post here links with findings about which environment variables are commonly used for GH, AzDO, and other typical repo integrations? thanks!

**Comment by Freia3** [comment]
GITHUB_TOKEN https://registry.terraform.io/providers/integrations/github/latest/docs
GITLAB_TOKEN https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs
AZDO_PERSONAL_ACCESS_TOKEN https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs

Could't find anything for bitbucket.
