### ISSUE TITLE
[FEATURE] Allow omitting subscription ID when using Azure CLI authentication

### ISSUE THREAD

**Issue by sdebruyn** [databrickslabs/terraform-provider-databricks#304]
The Azure CLI has a default subscription set. This subscription ID is used by the Azure RM Provider when you use Azure CLI authentication (unless you override it). The Databricks provider should support the CLI in the same way.

Examples: https://www.terraform.io/docs/providers/azurerm/guides/azure_cli.html

**Comment by nfx** [comment]
it's implemented as making a separate call to `az cli`. though i wonder how many people would actually need it, because if we specify `azure_workspace_resource_id`, we don't need to specify the subscription. I already feel like we have too many authentication options, which makes testing all possible cases harder.

PR it in with extensive coverage or let's wait for 10 different votes for it.

**Comment by nfx** [comment]
Subscription ID can be retrieved by

```
data "azurerm_client_config" "current" {
}

provider "databricks" {
    // ...
    azure_subscription_id =. data.azurerm_client_config.current.subscription_id
}
```
