### ISSUE TITLE
[FEATURE] Add option to skip waiting of library installation

### ISSUE THREAD

**Issue by lucas-corsi** [databrickslabs/terraform-provider-databricks#315]
Library resource always waits for library installation. I would like an option to skip this because it is not important to have a library installed for some use cases. Otherwise, it would be great if there is a way to set the timeouts instead of using default timeouts.

The issue/feature is related to this function https://github.com/databrickslabs/terraform-provider-databricks/blob/732b3f01224658d9ee01a594f3be1e5d27a613f8/compute/resource_cluster.go#L183

**Comment by nfx** [comment]
It’s already possible to set timeouts on cluster resource, where default is 30 minutes. Library await timeout is currently 5, so yes, it should be adjusted to follow cluster-level one. The change should also go along with context-aware refactoring of cluster resource (next logical phase of sdk2 migration).

Regarding making library install skipping: can you describe the use-cases where it’s needed? If library isn’t installed on a cluster, then workload requiring that library will fail, essentially having the failed resource. This is undesirable from Terraform logic perspective.

There’s a fast path, which doesn’t wait for library install, but it’s only during refresh state phase.

**Comment by lucas-corsi-ifood** [comment]
Hi, @nfx thanks for the information.

An example is when I only want to have a cluster versioned on git, and when I try to run a terraform plan command, this will wait for the entire timeout if it is necessary and the plan command takes a lot of time. Also, sometimes some libraries stay at pending status for a long time in Databricks, I don't know why this happens. And because of that, at the end of the timeout, the plan/apply command crashes without allowing the termination of the plan command or applying in other resources. But in this case, it is an exploration cluster trying to install an "on-all-clusters" library. This lib is not too important, is more like a best-effort behavior, in other words, is only "nice to have" because it is like an agent.

**Comment by nfx** [comment]
@lucas-corsi-ifood 

> have a cluster versioned on git, and when I try to run a terraform plan command, this will wait for the entire timeout if it is necessary and the plan command takes a lot of time

is it for new or existing clusters? if cluster is existing, is it running or or terminated? Perhaps [waitForLibrariesInstalled](https://github.com/databrickslabs/terraform-provider-databricks/blob/732b3f01224658d9ee01a594f3be1e5d27a613f8/compute/resource_cluster.go#L175) should be removed from read method then.

> Also, sometimes some libraries stay at pending status for a long time in Databricks, I don't know why this happens.

is there anything common for all of those libraries? e.g. pending for a long time if installed with provider or also the case when installed with UI?

> But in this case, it is an exploration cluster trying to install an "on-all-clusters" library

please note, that provider *is not using* [attachToAllClusters](https://docs.databricks.com/dev-tools/api/1.2/index.html#library-management) API (which is not supported since 2017), but it uses [latest libraries API](https://docs.databricks.com/dev-tools/api/latest/libraries.html). 

typically, Terraform is used to manage all resources. If you manage resources outside of terraform (like installing library on all clusters), it might be not possible for terraform to know about those changes. On the other hand, we may add a check to wait for statuses only in `ClusterLibraryList` of this resource.

**Comment by nfx** [comment]
@lucas-corsi released in 0.2.7
