### ISSUE TITLE
Handle HTTP 403 responses nicer

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#821]
Debugging authentication with 20 different parameters is frequently frustrating, especially for TF first-time users. 

Enrich every HTTP 403 error with [niceError](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/common/client.go#L243-L254) wrapper. As well as adding what authorizer was used for specific request, as people frequently forget about `~/.databrickscfg` having configured profiles.

cc @pohlposition

**Comment by pohlposition** [comment]
Just to add color here:

I'm a TF newbie creating my first ever TF script, and of course I've not gone through a proper tutorial :)

I managed to get a script working that created a workspace from the account (AWS).

I then got stuck when trying to create a PAT token.

I used the TF_LOG=DEBUG to uncover that the workspace provider was being authenticated using a token from my databrickscfg file.  This file had been created many months ago and included a token for a completely separate workspace.

I would have expected the databricks provider to be authenticated using the username and password that I had supplied in the .tf script.  

The DEBUG setting was useful so that I could discover where the credentials were being pulled from.  Since this is my first time using TF, it was confusing to understand the flow.

**Comment by nfx** [comment]
@pohlposition yes, this issue is to shorter time-to-working workspace in cases like yours.

**Comment by nfx** [comment]
This one is very similar to #836

**Comment by nfx** [comment]
Reopening this issue. Scope of this work would include refactoring authorizer to return two values: label ("serge@me.com through ~/.databrickscfg", "079945-3545-... through Azure CLI", ...) and request visitor. Perhaps we can even try to force auth as provider conf.

**Comment by nfx** [comment]
Not to forget, but special handling of empty host on data resources should be added: ignoring Databricks CLI auth, as this will finally force all users to explicitly add "depends_on" block to data resources, even for environment-configured providers.
