### ISSUE TITLE
databricks_group_member resource is too inflexible

### ISSUE THREAD

**Issue by anthonybench** [databrickslabs/terraform-provider-databricks#833]
Hello!

It would be widely more useful if the `databricks_group` resource could have a members field that took usernames (since they already have to be unique) instead of user ids, like:
```
resource "databricks_group" "group" {
  display_name                        = var.group.display_name
  allow_cluster_create             = var.group.can_create_cluster
  allow_instance_pool_create = var.group.can_create_pool
  allow_sql_analytics_access = var.group.can_access_sql
  workspace_access               = var.group.workspace_access
  members                               = [
    "flop@gmail.com"
    "blop@gmail.com"
  ]
}
```

**Comment by nfx** [comment]
I'll leave it open for a month and if it gets 50 votes and/or comments, we'll see if it makes sense to implement it.

Suggested feature will introduce a second way of managing group membership, which is highly likely to confuse users and become another source of support tickets.

Specifying members by name instead of ID would definitely not be implemented, as groups may have other groups or service principals as members, which have different API search paths. This would unnecessarily increase amount of API calls by orders of magnitude.

**Comment by nfx** [comment]
it's been two weeks and there's no way this issue to get 50 votes. closing it.

**Comment by FnayouSeif** [comment]
in case some lost spirit was wandering and stumbled upon this, it is possible to dynamically assign a list of users to a group. 
Found here in the community section: https://community.databricks.com/t5/data-engineering/terraform-create-multiple-db-user/td-p/11024
